"""Add captured pieces columns

Revision ID: 73ddc188761f
Revises: b1bef8d7b1ea
Create Date: 2024-08-14 16:45:00.116112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ddc188761f'
down_revision = 'b1bef8d7b1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('human_captured_pieces', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('computer_captured_pieces', sa.Integer(), nullable=True))
        batch_op.alter_column('game_over',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('game_over',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_column('computer_captured_pieces')
        batch_op.drop_column('human_captured_pieces')

    # ### end Alembic commands ###
