"""added current_user column

Revision ID: 7f68e19820ba
Revises: 2bff6fb5bbd7
Create Date: 2024-08-05 00:41:35.689592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f68e19820ba'
down_revision = '2bff6fb5bbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_user', sa.String(length=10), nullable=False,server_default='Human'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('current_user')

    # ### end Alembic commands ###
