"""removed curren_user column

Revision ID: a89a11c7b407
Revises: 7f68e19820ba
Create Date: 2024-08-05 23:25:32.853207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89a11c7b407'
down_revision = '7f68e19820ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('current_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_user', sa.VARCHAR(length=10), server_default=sa.text("'Human'::character varying"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
